hibahs/urls.py
from django.urls import path
from .admin import UploadedFile_list  # Import your custom admin class
from . import views
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from .views import print_item_view, delete_uploaded_view, show_prediction_view, delete_prediction_view





urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('print/<int:item_id>', print_item_view, name='print_item_view'), 
    path('delete_uploaded/<int:item_id>', delete_uploaded_view, name='delete_uploaded_view'), 
    path('item/<int:item_id>/', show_prediction_view, name='show_prediction_view'),
    path('delete_prediction/<int:item_id>', delete_prediction_view, name='delete_prediction_view'), 
    # path('uploadedfile', print_item_view, name='print_item_view'),
    # *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),

    


   ]

indriproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path("hibahs/", include("hibahs.urls")),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/admin/', permanent=True))
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView


urlpatterns = [
    path("hibahs/", include("hibahs.urls")),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/admin/', permanent=True))
]
    

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hibahs/models.py
from django.db import models

# Create your models here.
class PatientData(models.Model):
	GENDER_CHOICES = ( 
		('L', 'Laki-laki'), 
		('P', 'Perempuan'), 
	)

	patientName = models.CharField('Nama Pasien', max_length = 225)
	patientBirthDate = models.DateField('Tanggal Lahir', auto_now_add=False, auto_now=False)
	patientGender = models.CharField('Jenis Kelamin', max_length = 1, choices=GENDER_CHOICES, default='L')
	patientID = models.CharField('No Pasien', max_length = 16, unique=True, default=None)

	def __str__(self):
		return self.patientName

	class Meta:
		verbose_name_plural = 'Data Pasien'  # Change the display name here
	
	

class UploadedFile(models.Model):
	patientName = models.ForeignKey(PatientData, on_delete=models.CASCADE)
	image = models.FileField(upload_to='uploads/')
	annotation = models.FileField(upload_to='uploads/')
	imageDate = models.DateField('Tanggal Image diambil (mm/dd/yyyy)', auto_now_add=False, auto_now=False)
	uploaded_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		 return f"{self.image}"


	def patient_data(self):
		return self.patientName

	
class CroppedImage(models.Model):
	rawImage = models.ForeignKey(UploadedFile, on_delete=models.CASCADE)
	image = models.FileField(upload_to='static/')
	predictionResult = models.TextField(null=True, blank=True)
	predictionDate = models.DateField('Tanggal Image diprediksi (mm/dd/yyyy)', auto_now_add=False, auto_now=False)
	uploaded_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f"{self.image}"

hibahs/forms.py
from django import forms
from .models import UploadedFile, PatientData
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result


class PatientChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return f'{obj.patientNationalID} - {obj.patientName}'

def validate_file_type(value):
    if not value.name.lower().endswith(('.png', '.jpg', '.jpeg')):
        raise ValidationError(_('File type is not supported. Only PNG and JPEG are allowed.'))

class UploadFileForm(forms.ModelForm):
    patientName = PatientChoiceField(
        queryset= PatientData.objects.all(),
        empty_label='Pilih Nama Pasien',  # Remove the empty label (optional)
        to_field_name='id'
    )
    
    image = MultipleFileField()
    annotation = MultipleFileField()

    class Meta:
        model = UploadedFile
        fields = ['image', 'annotation', 'patientName', 'imageDate']

    imageDate = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}),
        label='Tanggal Diambil',
    )

    document = forms.FileField(validators=[validate_file_type])    



class PatientData(forms.ModelForm):
    class Meta:
        model = PatientData

        widgets = {
            'patientGender': forms.RadioSelect(),
        }

        fields = [
            "patientNationalID",
            "patientName",
            "patientGender",
            "patientBirthDate"
        ]

hibahs/views.py
from django.contrib.admin.views.decorators import staff_member_required

from django.shortcuts import render, redirect, get_object_or_404
from .models import UploadedFile, PatientData as PatientDataModel, CroppedImage
from django.http import HttpResponse
from django.urls import reverse 
from django.contrib import messages


def print_item_view(request, item_id):
    item = get_object_or_404(UploadedFile, id=item_id)
    prediction_results = CroppedImage.objects.filter(rawImage_id=item.id)

    data_to_print = UploadedFile.objects.filter(id=item.id)

    return render(request, "inference_print.html", {"data_to_print":data_to_print, "prediction_results": prediction_results})

def delete_uploaded_view(request, item_id):
	item = get_object_or_404(UploadedFile, id=item_id)

	file_to_delete = UploadedFile.objects.filter(id=item.id)
                
	context = {'file_to_delete': file_to_delete}

	action = request.POST.get('action')

	if action == 'verify':
		selected_file = request.POST.get('idPrint')
		file_to_delete = UploadedFile.objects.filter(id=selected_file)

		entered_password = request.POST.get('password')
		user = request.user
		if user.check_password(entered_password):
			file = get_object_or_404(UploadedFile, id=selected_file)
			file.delete()
			messages.success(request, 'Data Berhasil dihapus')
			return redirect('../admin/hibahs/uploadedfile/')
		else:
			messages.error(request, 'Password salah')
			return render(request, "delete_image.html", {'password_error': True, 'file_to_delete': file_to_delete})

	return render(request, "delete_image.html",  context)

def show_prediction_view(request, item_id):
	predicted_images = CroppedImage.objects.filter(rawImage_id=item_id)

	return render(request, "inference_output.html", {'predicted_images':predicted_images})


def delete_prediction_view(request, item_id):
	item = get_object_or_404(CroppedImage, id=item_id)

	file_to_delete = CroppedImage.objects.filter(id=item.id)
                
	context = {'file_to_delete': file_to_delete}

	action = request.POST.get('action')

	if action == 'verify':
		selected_file = request.POST.get('idPrint')
		file_to_delete = CroppedImage.objects.filter(id=selected_file)

		entered_password = request.POST.get('password')
		user = request.user
		if user.check_password(entered_password):
			file = get_object_or_404(CroppedImage, id=selected_file)
			file.delete()
			messages.success(request, 'Data Berhasil dihapus')
			return redirect('../admin/hibahs/uploadedfile/')
		else:
			messages.error(request, 'Password salah')
			return render(request, "delete_prediction.html", {'password_error': True, 'file_to_delete': file_to_delete})

	return render(request, "delete_prediction.html",  context)

hibahs/templates/delete_image.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls static admin_modify %}
{% block branding %}
    <h1 id="site-name"><a href="{% url 'admin:index' %}">InDRI (Intelligent Diagnosis of Radiology Images)</a></h1>
{% endblock %}
{% block content %}
<head>
	
	
</head>
<body>
	Silahkan masukkan password anda jika ingin hapus data 

<table>
	{% for patient in patient_to_delete %}
	<tr>
		<td>
			Name Pasien
		</td>
		<td>
			: {{ patient.patient_data.patientName }} 
		</td>
	</tr>
	<tr>
		<td>
			No Pasien
		</td>
		<td>
			: {{ patient.patient_data.patientID }}
			
		</td>
	</tr>
	<tr>
		<td>
			Gambar Asli
		</td>
		<td>
			<img src="/media/{{ patient.file }}" width="100"></a>
		</td>
	</tr>
	<tr>

		<form method="post" action="">
		{% csrf_token %}
			<td>
				<input type="password" name="password">
				<input type="hidden" name="idPrint" value="{{ patient.id }}">
			</td>
			<td>
				<button name="action" value="verify" class="button is-danger">Hapus</button>
			</td>
		</form>
	</tr>
	{% endfor %}
</table>



{% endblock %}

hibahs/templates/delete_prediction.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls static admin_modify %}
{% block branding %}
    <h1 id="site-name"><a href="{% url 'admin:index' %}">Pap Smear Detection</a></h1>
{% endblock %}
{% block content %}
<head>
	
	
</head>
<body>
	Silahkan masukkan password anda jika ingin hapus data 

<table>
	{% for file in file_to_delete %}
	<tr>
		<td>
			Name Pasien
		</td>
		<td>
			: {{ file.rawImage.patient_data.patientName }} 
		</td>
	</tr>
	<tr>
		<td>
			No Pasien
		</td>
		<td>
			: {{ file.rawImage.patient_data.id }}
			
		</td>
	</tr>
	<tr>
		<td>
			Gambar Asli
		</td>
		<td>
			<img src="/media/static/{{ file.image }}" width="100"></a>
		</td>
	</tr>
	<tr>

		<form method="post" action="">
		{% csrf_token %}
			<td>
				<input type="password" name="password">
				<input type="hidden" name="idPrint" value="{{ file.id }}">
			</td>
			<td>
				<button name="action" value="verify" class="button is-danger">Hapus</button>
			</td>
		</form>
	</tr>
	{% endfor %}
</table>



{% endblock %}

hibahs/templates/inference_output.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls static admin_modify %}

{% load mathfilters %}

{% block branding %}
    <h1 id="site-name"><a href="{% url 'admin:index' %}">Pap Smear Detection</a></h1>
{% endblock %}

<html>
<head>
    <title>Upload Results</title>
    
</head>
{% block content %}

<body>
    <h1>Results</h1>

    <table width="100%">
        <thead>
            <tr>
                <th>Gambar Asli</th>
                <th>Hasil Prediksi</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
        {% for data in predicted_images %}
            <tr>

                <td>
                    <img src="/media/static/{{ data.image }}" width="224" height="224">
                </td>
                <td>
                    <p>Model mendiagnosis bahwa gambar yang diupload terindikasi {{ data.predictionResult }}</p>
                </td>
                <td>
                    <a href="{% url 'delete_prediction_view' data.id %}" class="button" name="action" value="delete" style="background-color: #ba2121; color: white;">Hapus</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}



</body>

</html>

hibahs/templates/inference_print.html
{% load mathfilters %}
{% block content %}
<head>
	<script>
		window.onload = function() {
			window.print();
		};
	</script>
	<style>
		@media print {
		   body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            -webkit-print-color-adjust: exact;
	        }

	        header {
	            background-color: #417690;
	            color: white;
	            padding: 10px;
	            text-align: center;
	        }

	        footer {
	            background-color: #333;
	            color: white;
	            padding: 10px;
	            text-align: center;
	            position: fixed;
	            bottom: 0;
	            width: 100%;
	        }


		}



	        header {
	            background-color: #417690;
	            color: white;
	            padding: 10px;
	            text-align: center;
	        }

	        footer {
	            background-color: #333;
	            color: white;
	            padding: 10px;
	            text-align: center;
	            position: fixed;
	            bottom: 0;
	            width: 100%;
	        }
	</style>
</head>
<body>
	<header>
        <h1>Pap Smear Detection</h1>
        {% comment %} <h2>(Intelligent Diagnosis of Radiology Images)</h2> {% endcomment %}
    </header>
<center><h1>HASIL PREDIKSI</h1></center>

{% if data_to_print %}
<table>
	{% for data in data_to_print %}
	<tr>
		<td>
			Name Pasien
		</td>
		<td>
			: {{ data.patient_data.patientName }} 
		</td>
	</tr>
	<tr>
		<td>
			No Pasien
		</td>
		<td>
			: {{ data.patient_data.patientID }}
		</td>
	</tr>
	<tr>
		<td>
			Tanggal Lahir
		</td>
		<td>
			: {{ data.patient_data.patientBirthDate }}
		</td>
	</tr>
	<tr>
		<td>
			Jenis Kelamin
		</td>
		<td>
			: {{ data.patient_data.get_patientGender_display }}
		</td>
	</tr>
	<tr>
		<td>
			Tanggal Gambar Diambil 
		</td>
				<td>
                   : {{ data.imageDate|date:"Y-m-d" }}
                </td>
			</tr>
	{% endfor %}
</table>

		<table width="100%" border="0">
            <thead>
                <tr>
                    <th>Gambar Asli</th>
                </tr>
            </thead>
            <tbody>

			{% for data in data_to_print %}
				
				<br><br>

			<tr>
				<td align="center" valign="middle">
					<img src="/media/{{ data.image }}"  width="224" height="224">
                </td>
            </tr>
            </tbody>
			<thead>
                <tr>
                    <th>Hasil Prediksi</th>
                </tr>
            </thead>
			<tbody>
				<tr>
					{% for item in prediction_results %}
						<td align="center">
							<img src="/media/static/{{ item.image }}" width="224" height="224">
							<p>Model mendiagnosis bahwa gambar berikut terindikasi {{ item.predictionResult }}</p>
						</td>
					{% endfor %}
				</tr>
			</tbody>
        </table>
		</br>
        <footer>
        		<p>&copy; 2024 BDSRC and AIRDC | Binus University. All Rights Reserved.</p>
    	</footer>
    </body>
			{% endfor%}

			{% endif %}
{% endblock %}

hibahs/templates/patient_with_image.html
<!-- fileuploads/templates/upload_and_display.html -->
{% extends "admin/base_site.html" %}
{% load i18n admin_urls static admin_modify %}

{% load mathfilters %}

{% block content %}
<head>
  <style>
    /* Modal styles */
    .modal {
        display: none; 
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.7);
        z-index: 999; /* Adjust the z-index value as needed */
    }

    /* Modal content styles */
    .modal-content {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        background-color: #fff;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
        text-align: center;
    }

    /* Loader styles (you can define your loader styles here) */
    .loader {
        border: 4px solid #f3f3f3; /* Light gray border */
        border-top: 4px solid #3498db; /* Blue border */
        border-radius: 50%;
        width: 40px;
        height: 40px;
        animation: spin 2s linear infinite; /* Spinning animation */
    }

    @keyframes spin {
        0% { transform: rotate(0deg); }
        100% { transform: rotate(360deg); }
    }
</style>
</head>
<body>
        {% if alert_message %}
            {{ alert_message }}"
            
        {% endif %}


        <div id="loaderModal" class="modal">
                <div class="modal-content">
                    <div class="loader"></div>
                </div>
        </div>

        <h3>Data Pasien:</h3>
        <h1>Nama Pasien:  {{ object.patientName }}</h1>

        <table width="100%">
            <thead>
                <tr>
                    <th></th>
                    <th>Gambar Asli</th>
                    <th>Tanggal Gambar diambil</th>
                    <th colspan="3"></th>
                </tr>
            </thead>
            <tbody>
            <form method="post" action="" onsubmit="showLoader()">
            {% for item in object.uploadedfile_set.all %}
                <tr>
                    {% if item in predicted_files %}
                        <td>
                            <input type="checkbox" name="selected_files" value="{{ item.id }}" disabled>
                        </td>
                    {% elif not item.diagnosisResult %}
                        <td>
                            <input type="checkbox" name="selected_files" value="{{ item.id }}" enabled>
                        </td>
                    {% endif %}

                    <td><a href="{{ item.image.url }}">
                        <img src="/media/{{ item.image.name }}" width="100"></a>
                    </td>

                    <td>
                        {{ item.imageDate|date:"Y-m-d" }} 
                    </td>
                    <td>
                        {% if item in predicted_files %}
                            <a a href="{% url 'print_item_view' item.id %}" class="button is-danger" name="action" value="print">Print</a>
                        {% endif %}
                    </td>
                    <td>
                        {% if item in predicted_files %}
                                <a href="{% url 'show_prediction_view' item.id %}" class="button" name="action" value="show" >Prediction</a>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'delete_uploaded_view' item.id %}" class="button" name="action" value="delete" style="background-color: #ba2121; color: white;">Hapus</a>
                    </td>
                </tr>
            </tbody>
            {% empty %}
                <li>No files uploaded yet.</li>
            {% endfor %}
            {% csrf_token %}
            <button type="submit" id="inference-button" class="button is-success is-fullwidth is-medium mt-5" name="action" value="inference">Inference</button>

            </form>
        </table>

        


</body>
<script>
        function showLoader() {
            var modal = document.getElementById('loaderModal');
            modal.style.display = 'block';
            // You can add more loading logic here if needed
        }

        
    </script>
{% endblock %}

hibahs/templates/upload_and_display.html
<!-- fileuploads/templates/upload_and_display.html -->
{% extends "admin/base_site.html" %}
<!-- {% load i18n admin_urls static admin_modify %} -->
{% block branding %}
    <h1 id="site-name"><a href="{% url 'admin:index' %}">Pap Smear Detection</a></h1>
{% endblock %}


<!DOCTYPE html>
<html>
<head>
   
</head>
<body>
    
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>

{% endblock %}        
</body>
</html>